import React from 'react';
import { Assignment } from '../../types';

export const AssignmentsTab: React.FC<{ assignments: Assignment[] }> = ({ assignments }) => {
  
  const handleDownload = (assignment: Assignment) => {
    const content = `
STANFORD ONLINE
COURSE ASSIGNMENT: ${assignment.title}
---------------------------------------------------
ESTIMATED HOURS: ${assignment.estimatedHours}

INSTRUCTIONS:
${assignment.description}

---------------------------------------------------
Generated by Cardinal Course Generator
`;
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${assignment.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_instructions.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-4xl mx-auto">
      <h2 className="text-3xl font-serif font-bold text-stanford-dark mb-8">Problem Sets & Assignments</h2>

      <div className="space-y-6">
        {assignments.map((assignment, idx) => (
          <div key={idx} className="flex flex-col md:flex-row bg-white border border-gray-200 rounded-sm overflow-hidden shadow-sm hover:shadow-md transition-shadow">
             <div className="bg-stanford-dark p-6 flex flex-col items-center justify-center text-white min-w-[150px]">
                <span className="text-4xl font-serif font-bold">{(idx + 1).toString().padStart(2, '0')}</span>
                <span className="text-xs uppercase tracking-widest opacity-75">Assignment</span>
             </div>
             <div className="p-6 flex-grow flex flex-col justify-between">
                <div>
                    <div className="flex justify-between items-start mb-2">
                        <h3 className="text-xl font-bold text-stanford-dark">{assignment.title}</h3>
                        <span className="text-sm font-semibold text-gray-500 bg-gray-100 px-3 py-1 rounded-full whitespace-nowrap">
                            ~{assignment.estimatedHours} Hours
                        </span>
                    </div>
                    <p className="text-gray-600 leading-relaxed mb-6">
                        {assignment.description}
                    </p>
                </div>
                
                <button 
                    onClick={() => handleDownload(assignment)}
                    className="text-stanford-red font-bold text-sm uppercase tracking-wider hover:bg-stanford-red hover:text-white border border-stanford-red px-4 py-2 rounded-sm w-fit transition-all flex items-center gap-2"
                >
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4-4m0 0l-4-4m4 4v12" />
                    </svg>
                    Download Instructions
                </button>
             </div>
          </div>
        ))}
      </div>
    </div>
  );
};