
import React, { useState } from 'react';
import { Assignment, GradingResult } from '../../types';
import { jsPDF } from 'jspdf';
import { gradeSubmission } from '../../services/geminiService';

export const AssignmentsTab: React.FC<{ assignments: Assignment[] }> = ({ assignments }) => {
  const [submissions, setSubmissions] = useState<{ [key: number]: string }>({});
  const [grades, setGrades] = useState<{ [key: number]: GradingResult }>({});
  const [loadingMap, setLoadingMap] = useState<{ [key: number]: boolean }>({});

  const handleDownload = (assignment: Assignment) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFont("times", "bold");
    doc.setFontSize(22);
    doc.setTextColor(140, 21, 21); // Stanford Red
    doc.text("STANFORD ONLINE", 20, 20);
    
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text(`Assignment: ${assignment.title}`, 20, 30);
    
    doc.setLineWidth(0.5);
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 35, 190, 35);

    // Info
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(`Estimated Effort: ${assignment.estimatedHours} Hours`, 20, 45);
    
    // Instructions
    doc.setFont("times", "bold");
    doc.setFontSize(14);
    doc.text("Instructions", 20, 55);
    
    doc.setFont("times", "normal");
    doc.setFontSize(12);
    const splitDescription = doc.splitTextToSize(assignment.description, 170);
    doc.text(splitDescription, 20, 65);
    
    let currentY = 65 + (splitDescription.length * 7);

    // Technical Requirements
    if (assignment.technicalRequirements && assignment.technicalRequirements.length > 0) {
        currentY += 10;
        doc.setFont("times", "bold");
        doc.setFontSize(14);
        doc.text("Technical Requirements", 20, currentY);
        
        currentY += 10;
        doc.setFont("times", "normal");
        doc.setFontSize(12);
        
        assignment.technicalRequirements.forEach((req) => {
            const splitReq = doc.splitTextToSize(`• ${req}`, 170);
            doc.text(splitReq, 20, currentY);
            currentY += (splitReq.length * 7);
        });
    }
    
    // Relevant Links
    if (assignment.relevantLinks && assignment.relevantLinks.length > 0) {
        currentY += 10;
        doc.setFont("times", "bold");
        doc.setFontSize(14);
        doc.text("Relevant Resources & Practice", 20, currentY);
        
        currentY += 10;
        doc.setFont("times", "normal");
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 255); // Blue links
        
        assignment.relevantLinks.forEach((link) => {
            const text = `• ${link.title}: ${link.url}`;
            const splitLink = doc.splitTextToSize(text, 170);
            doc.text(splitLink, 20, currentY);
            currentY += (splitLink.length * 7);
        });
    }

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text("Generated by Cardinal Course Generator", 20, 280);

    doc.save(`${assignment.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf`);
  };

  const handleSubmit = async (index: number, assignment: Assignment) => {
    const submissionText = submissions[index];
    if (!submissionText?.trim()) return;

    setLoadingMap(prev => ({ ...prev, [index]: true }));
    try {
        const result = await gradeSubmission(
            'Assignment',
            assignment.title,
            assignment.description + " " + assignment.technicalRequirements.join(" "),
            submissionText
        );
        setGrades(prev => ({ ...prev, [index]: result }));
    } catch (e) {
        console.error(e);
        alert("Grading failed. Please try again.");
    } finally {
        setLoadingMap(prev => ({ ...prev, [index]: false }));
    }
  };

  return (
    <div className="max-w-4xl mx-auto">
      <h2 className="text-3xl font-serif font-bold text-stanford-dark mb-8">Problem Sets & Assignments</h2>

      <div className="space-y-8">
        {assignments.map((assignment, idx) => (
          <div key={idx} className="flex flex-col bg-white border border-gray-200 rounded-sm overflow-hidden shadow-sm hover:shadow-md transition-shadow">
             <div className="flex flex-col md:flex-row border-b border-gray-100">
                <div className="bg-stanford-dark p-6 flex flex-col items-center justify-center text-white min-w-[150px]">
                    <span className="text-4xl font-serif font-bold">{(idx + 1).toString().padStart(2, '0')}</span>
                    <span className="text-xs uppercase tracking-widest opacity-75">Assignment</span>
                </div>
                <div className="p-6 flex-grow">
                    <div className="flex justify-between items-start mb-2">
                        <h3 className="text-2xl font-bold text-stanford-dark">{assignment.title}</h3>
                        <span className="text-sm font-semibold text-gray-500 bg-gray-100 px-3 py-1 rounded-full whitespace-nowrap">
                            ~{assignment.estimatedHours} Hours
                        </span>
                    </div>
                    <p className="text-gray-600 leading-relaxed">
                        {assignment.description}
                    </p>
                </div>
             </div>

             <div className="p-6 bg-stanford-fog grid md:grid-cols-2 gap-6">
                 <div>
                     <h4 className="font-bold text-stanford-dark mb-3 uppercase text-xs tracking-wider">Technical Specifications</h4>
                     <ul className="space-y-2">
                        {assignment.technicalRequirements?.map((req, rIdx) => (
                            <li key={rIdx} className="flex items-start gap-2 text-sm text-gray-700">
                                <span className="text-stanford-red font-bold mt-1">›</span>
                                {req}
                            </li>
                        ))}
                     </ul>
                 </div>
                 <div>
                     <h4 className="font-bold text-stanford-dark mb-3 uppercase text-xs tracking-wider">Relevant Practice & Links</h4>
                     <ul className="space-y-2">
                        {assignment.relevantLinks?.map((link, lIdx) => (
                            <li key={lIdx} className="flex items-start gap-2 text-sm">
                                <span className="text-blue-500 mt-1">
                                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" /></svg>
                                </span>
                                <a href={link.url} target="_blank" rel="noopener noreferrer" className="text-blue-700 hover:underline break-all">
                                    {link.title}
                                </a>
                            </li>
                        ))}
                     </ul>
                 </div>
             </div>
                
             <div className="p-4 bg-gray-50 border-t border-gray-200 flex flex-col gap-4">
                <div className="flex justify-end">
                    <button 
                        onClick={() => handleDownload(assignment)}
                        className="text-white bg-stanford-red hover:bg-[#721111] font-bold text-sm uppercase tracking-wider px-5 py-3 rounded-sm transition-all flex items-center gap-2 shadow-sm"
                    >
                        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4-4m0 0l-4-4m4 4v12" />
                        </svg>
                        Download PDF Instructions
                    </button>
                </div>

                <div className="border-t border-gray-200 pt-4 mt-2">
                    <h4 className="font-bold text-stanford-dark mb-2 text-sm uppercase tracking-wider">Student Submission</h4>
                    {!grades[idx] ? (
                        <div className="flex flex-col gap-3">
                            <textarea 
                                className="w-full p-3 border border-gray-300 rounded-sm font-sans text-sm focus:ring-2 focus:ring-stanford-red focus:border-transparent outline-none h-32"
                                placeholder="Paste your solution code, link to repository, or answer here..."
                                value={submissions[idx] || ''}
                                onChange={(e) => setSubmissions(prev => ({ ...prev, [idx]: e.target.value }))}
                            />
                            <button 
                                onClick={() => handleSubmit(idx, assignment)}
                                disabled={loadingMap[idx] || !submissions[idx]}
                                className="self-end bg-stanford-dark text-white px-6 py-2 rounded-sm text-sm font-semibold hover:bg-black disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                            >
                                {loadingMap[idx] ? 'Grading...' : 'Submit for Grading'}
                            </button>
                        </div>
                    ) : (
                        <div className="bg-white border-l-4 border-stanford-red p-4 shadow-sm animate-fade-in">
                            <div className="flex justify-between items-center mb-2">
                                <span className="font-bold text-lg text-stanford-dark">Grade: <span className={grades[idx].score >= 70 ? 'text-green-600' : 'text-red-600'}>{grades[idx].score}/100</span></span>
                                <button 
                                    onClick={() => setGrades(prev => { const n = {...prev}; delete n[idx]; return n; })}
                                    className="text-xs text-gray-400 underline hover:text-gray-600"
                                >
                                    Resubmit
                                </button>
                            </div>
                            <p className="text-gray-700 text-sm leading-relaxed">{grades[idx].feedback}</p>
                        </div>
                    )}
                </div>
             </div>
          </div>
        ))}
      </div>
    </div>
  );
};
