import React from 'react';
import { Assignment } from '../../types';
import { jsPDF } from 'jspdf';

export const AssignmentsTab: React.FC<{ assignments: Assignment[] }> = ({ assignments }) => {
  
  const handleDownload = (assignment: Assignment) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFont("times", "bold");
    doc.setFontSize(22);
    doc.setTextColor(140, 21, 21); // Stanford Red
    doc.text("STANFORD ONLINE", 20, 20);
    
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text(`Assignment: ${assignment.title}`, 20, 30);
    
    doc.setLineWidth(0.5);
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 35, 190, 35);

    // Info
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(`Estimated Effort: ${assignment.estimatedHours} Hours`, 20, 45);
    
    // Instructions
    doc.setFont("times", "bold");
    doc.setFontSize(14);
    doc.text("Instructions", 20, 55);
    
    doc.setFont("times", "normal");
    doc.setFontSize(12);
    const splitDescription = doc.splitTextToSize(assignment.description, 170);
    doc.text(splitDescription, 20, 65);
    
    let currentY = 65 + (splitDescription.length * 7);

    // Technical Requirements
    if (assignment.technicalRequirements && assignment.technicalRequirements.length > 0) {
        currentY += 10;
        doc.setFont("times", "bold");
        doc.setFontSize(14);
        doc.text("Technical Requirements", 20, currentY);
        
        currentY += 10;
        doc.setFont("times", "normal");
        doc.setFontSize(12);
        
        assignment.technicalRequirements.forEach((req) => {
            const splitReq = doc.splitTextToSize(`• ${req}`, 170);
            doc.text(splitReq, 20, currentY);
            currentY += (splitReq.length * 7);
        });
    }
    
    // Relevant Links
    if (assignment.relevantLinks && assignment.relevantLinks.length > 0) {
        currentY += 10;
        doc.setFont("times", "bold");
        doc.setFontSize(14);
        doc.text("Relevant Resources & Practice", 20, currentY);
        
        currentY += 10;
        doc.setFont("times", "normal");
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 255); // Blue links
        
        assignment.relevantLinks.forEach((link) => {
            const text = `• ${link.title}: ${link.url}`;
            const splitLink = doc.splitTextToSize(text, 170);
            doc.text(splitLink, 20, currentY);
            currentY += (splitLink.length * 7);
        });
    }

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text("Generated by Cardinal Course Generator", 20, 280);

    doc.save(`${assignment.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf`);
  };

  return (
    <div className="max-w-4xl mx-auto">
      <h2 className="text-3xl font-serif font-bold text-stanford-dark mb-8">Problem Sets & Assignments</h2>

      <div className="space-y-8">
        {assignments.map((assignment, idx) => (
          <div key={idx} className="flex flex-col bg-white border border-gray-200 rounded-sm overflow-hidden shadow-sm hover:shadow-md transition-shadow">
             <div className="flex flex-col md:flex-row border-b border-gray-100">
                <div className="bg-stanford-dark p-6 flex flex-col items-center justify-center text-white min-w-[150px]">
                    <span className="text-4xl font-serif font-bold">{(idx + 1).toString().padStart(2, '0')}</span>
                    <span className="text-xs uppercase tracking-widest opacity-75">Assignment</span>
                </div>
                <div className="p-6 flex-grow">
                    <div className="flex justify-between items-start mb-2">
                        <h3 className="text-2xl font-bold text-stanford-dark">{assignment.title}</h3>
                        <span className="text-sm font-semibold text-gray-500 bg-gray-100 px-3 py-1 rounded-full whitespace-nowrap">
                            ~{assignment.estimatedHours} Hours
                        </span>
                    </div>
                    <p className="text-gray-600 leading-relaxed">
                        {assignment.description}
                    </p>
                </div>
             </div>

             <div className="p-6 bg-stanford-fog grid md:grid-cols-2 gap-6">
                 <div>
                     <h4 className="font-bold text-stanford-dark mb-3 uppercase text-xs tracking-wider">Technical Specifications</h4>
                     <ul className="space-y-2">
                        {assignment.technicalRequirements?.map((req, rIdx) => (
                            <li key={rIdx} className="flex items-start gap-2 text-sm text-gray-700">
                                <span className="text-stanford-red font-bold mt-1">›</span>
                                {req}
                            </li>
                        ))}
                     </ul>
                 </div>
                 <div>
                     <h4 className="font-bold text-stanford-dark mb-3 uppercase text-xs tracking-wider">Relevant Practice & Links</h4>
                     <ul className="space-y-2">
                        {assignment.relevantLinks?.map((link, lIdx) => (
                            <li key={lIdx} className="flex items-start gap-2 text-sm">
                                <span className="text-blue-500 mt-1">
                                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" /></svg>
                                </span>
                                <a href={link.url} target="_blank" rel="noopener noreferrer" className="text-blue-700 hover:underline break-all">
                                    {link.title}
                                </a>
                            </li>
                        ))}
                     </ul>
                 </div>
             </div>
                
             <div className="p-4 bg-gray-50 border-t border-gray-200 flex justify-end">
                <button 
                    onClick={() => handleDownload(assignment)}
                    className="text-white bg-stanford-red hover:bg-[#721111] font-bold text-sm uppercase tracking-wider px-5 py-3 rounded-sm transition-all flex items-center gap-2 shadow-sm"
                >
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4-4m0 0l-4-4m4 4v12" />
                    </svg>
                    Download PDF Instructions
                </button>
             </div>
          </div>
        ))}
      </div>
    </div>
  );
};