import React, { useState } from 'react';
import { CourseData } from '../types';
import { CourseHeader } from './CourseHeader';
import { HomeTab } from './tabs/HomeTab';
import { SyllabusTab } from './tabs/SyllabusTab';
import { ReadingsTab } from './tabs/ReadingsTab';
import { AssignmentsTab } from './tabs/AssignmentsTab';
import { ProjectsTab } from './tabs/ProjectsTab';
import { CapstoneTab } from './tabs/CapstoneTab';

interface CourseViewProps {
  course: CourseData;
  onReset: () => void;
}

export const CourseView: React.FC<CourseViewProps> = ({ course, onReset }) => {
  const [activeTab, setActiveTab] = useState('Home');

  const renderTab = () => {
    switch (activeTab) {
      case 'Home': return <HomeTab course={course} />;
      case 'Syllabus': return <SyllabusTab modules={course.modules} />;
      // Pass modules to ReadingsTab because readings are now nested in modules
      case 'Readings': return <ReadingsTab modules={course.modules} />;
      case 'Assignments': return <AssignmentsTab assignments={course.assignments} />;
      case 'Projects': return <ProjectsTab projects={course.projects} />;
      case 'Capstone': return <CapstoneTab capstone={course.capstone} />;
      default: return <HomeTab course={course} />;
    }
  };

  return (
    <div className="min-h-screen bg-white">
      <CourseHeader course={course} activeTab={activeTab} setActiveTab={setActiveTab} />
      
      <main className="container mx-auto px-6 py-12 min-h-[60vh]">
        {renderTab()}
      </main>

      <footer className="bg-stanford-dark text-white py-12 mt-12">
        <div className="container mx-auto px-6 flex flex-col md:flex-row justify-between items-center">
          <div className="mb-4 md:mb-0">
             <span className="font-serif text-xl font-bold">Stanford University</span>
             <p className="text-gray-400 text-sm mt-1">Generated by Cardinal Course AI</p>
          </div>
          <button 
            onClick={onReset}
            className="text-gray-300 hover:text-white border border-gray-600 hover:border-white px-4 py-2 rounded-sm text-sm uppercase tracking-wider transition-all"
          >
            Create Another Course
          </button>
        </div>
      </footer>
    </div>
  );
};